name: pytype check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pytypes checker
      uses: KathanSheth/MyBookStore@master
      with:
        args: -d import-error
